### ISSUE TITLE
error: Activating Swift extension failed: Failed to find lldb-dap in Swift toolchain

### ISSUE THREAD

**Issue by thaneliu** [swiftlang/vscode-swift#1077]
## Environment:
- CPU: Intel x64
- OS: macOS Sequoia Version 15.0
- Xcode: Xcode Version 16.0(16A242d)
- VSCode: VSCode Version: 1.93.1
- vscode-swift: v1.110

## Reproduce:
1. upgrade to macOS Squoia 15.0
2. upgrade to Xcode 16.0
3. upgrade to VSCode 1.93.1
4. create a iOS App project by XCode 16.0
5. open the project by VSCode

## Screenshots:
<img width="210" alt="image" src="https://github.com/user-attachments/assets/e3adc956-091e-4a35-919a-dddae490422b">

<img width="566" alt="image" src="https://github.com/user-attachments/assets/af5591d6-8daa-4953-a2f1-f3132a9f446e">

<img width="1084" alt="image" src="https://github.com/user-attachments/assets/f01bfb35-45b2-4fcf-8f66-ec71dc493efb">

<img width="296" alt="image" src="https://github.com/user-attachments/assets/230c8762-f1bc-4507-95ab-c45df883e4b2">

**Comment by plemarquand** [comment]
@fearnliu could you run `> Swift: Capture VS Code Swift Diagnostic Bundle`, choose Minimal Bundle and attach the two files to this issue?

**Comment by fearnliu** [comment]
> @fearnliu could you run `> Swift: Capture VS Code Swift Diagnostic Bundle`, choose Minimal Bundle and attach the two files to this issue?
> 
> Have you updated to the newest Xcode (Xcode 16)?

Hello~ thanks for your reply.

I have run the command in VScode. there are two files in attach files.
yep~, Xcode is Version 16.0(has upgraded to the latest version in Mac App Store recently), and the project "SmartAlarmClock"(ios APP) was created by Xcode 16. I have just opened the project in my VSCode.

By the way, my mac cpu is intel x64.

[extension-logs.txt](https://github.com/user-attachments/files/17044807/extension-logs.txt)
[settings.txt](https://github.com/user-attachments/files/17044811/settings.txt)

**Comment by matthewbastien** [comment]
@fearnliu I've addressed the failed activation with my most recent PR, but it's not really going to solve your issue if you want to use `lldb-dap` (if you're not enabling `swift.debugger.useDebugAdapterFromToolchain` then you're probably fine for now). I'm interested in determining why the extension couldn't identify your `lldb-dap` executable. Could you try running `xcrun --find lldb-dap` in your terminal and provide the output here?

**Comment by award999** [comment]
@fearnliu could you try running `xcrun --find lldb-dap` in your terminal and provide the output here?

**Comment by award999** [comment]
@fearnliu we're closing, please reopen if you're still seeing

**Comment by joergbattermann** [comment]
Still seeing this today @matthewbastien / @award999 with most recent macOS 26.1 (25B78) / Xcode 26.1 (17B55).

VS Code:

Version: 1.105.1
Commit: 7d842fb85a0275a4a8e4d7e040d2625abbf7f084
Date: 2025-10-14T22:33:36.618Z (3 wks ago)
Electron: 37.6.0
ElectronBuildId: 12502201
Chromium: 138.0.7204.251
Node.js: 22.19.0
V8: 13.8.258.32-electron.0
OS: Darwin arm64 25.1.0

.. with Swift / _swiftlang.swift-vscode_ extension v2.14.0.

`xcrun --find lldb-dap` returns `/Library/Developer/CommandLineTools/usr/bin/lldb-dap`


Steps to reproduce:

- Open macOS command line
- type
  - `mkdir <_yourdirectorynamehere_>`
  - `cd <_yourdirectorynamehere_>`
  -  `swift package init --type executable --name demo`
  -  `code .`
  - .. and try to run or debug it
- Expected result: code is compiled and run resulting into "Hello, world!" output
- Actual result: 

<img width="800" height="780" alt="Image" src="https://github.com/user-attachments/assets/e1fe97f2-bcea-4be3-85f9-9d615e855de1" />

.. content of the opened launch.json file shows this:

```
{
    "configurations": [
        {
            "type": "swift",
            "request": "launch",
            "args": [],
            "cwd": "${workspaceFolder:demo}",
            "name": "Debug demo",
            "target": "demo",
            "configuration": "debug",
            "preLaunchTask": "swift: Build Debug demo"
        },
        {
            "type": "swift",
            "request": "launch",
            "args": [],
            "cwd": "${workspaceFolder:demo}",
            "name": "Release demo",
            "target": "demo",
            "configuration": "release",
            "preLaunchTask": "swift: Build Release demo"
        }
    ]
}
```

Mind you, the `swift` command is available in the PATH just fine but while the dialog above says it "_failed to find_"  the `lldb-dap` command in `/Library/Developer/CommandLineTools/usr` .. it actually _is_ in `/Library/Developer/CommandLineTools/usr/bin/lldb-dap`.

So either the underlying logic doesn't look recursively in the path / doesn't look into ./bin/ there.. or something else is going on as the lldb-dap command sure _does_ exist there:

<img width="1646" height="118" alt="Image" src="https://github.com/user-attachments/assets/e4293b44-32e6-473f-bb63-bfe1a1d7105b" />

**Comment by matthewbastien** [comment]
@joergbattermann thanks for the report! Can you upload a **minimal** (this issue shouldn't require a full diagnostics bundle to diagnose) diagnostics bundle? Run the VS Code command `Swift: Capture Diagnostic Bundle` and then upload it to this issue.

**Please review the bundle before uploading it as it may contain sensitive information.**

**Comment by joergbattermann** [comment]
Sure thing Matthew. Mind you I had already updated VS Code to 1.106 that was released earlier this morning, so that bit of my system's info is quasi now:

-- VS Code -- 
```
Version: 1.106.0
Commit: ac4cbdf48759c7d8c3eb91ffe6bb04316e263c57
Date: 2025-11-11T16:02:25.943Z (1 day ago)
Electron: 37.7.0
ElectronBuildId: 12597478
Chromium: 138.0.7204.251
Node.js: 22.20.0
V8: 13.8.258.32-electron.0
OS: Darwin arm64 25.1.0
```

But anyway, the minimal diagnostic bundle is this one: [vscode-diagnostics-2025-11-12T10-27-44-08-00.zip](https://github.com/user-attachments/files/23507014/vscode-diagnostics-2025-11-12T10-27-44-08-00.zip) and the full one's this one: [vscode-diagnostics-2025-11-12T10-30-12-08-00.zip](https://github.com/user-attachments/files/23507058/vscode-diagnostics-2025-11-12T10-30-12-08-00.zip) .. didn't find any personal information so have at it & please let me know if/what else you might need.

Thanks!

**Comment by matthewbastien** [comment]
Thank you for the logs! I'm able to reproduce this locally now. Now to figure out why it's broken...

**Comment by joergbattermann** [comment]
Great! Lmk if/whenever there's anything I can do to help/test or sth.

**Comment by matthewbastien** [comment]
So, the issue lies with how the Swift extension determines whether or not you're using an Xcode toolchain. If you `xcode-select --switch /Applications/Xcode.app` then you should be able to get back up and running until a fix is ready.

**Comment by joergbattermann** [comment]
Yep, I can confirm that manually switching over (or back?) to / `xcode-select` -ing the _Xcode.app_ bundled toolchain works 👍🏻

Should it in theory also work if one had the _CommandLineTools_ installed.. either in parallel to the full Xcode.app or just the _CommandLineTools_ themselves?

**Comment by matthewbastien** [comment]
> Should it in theory also work if one had the CommandLineTools installed.. either in parallel to the full Xcode.app or just the CommandLineTools themselves?

The extension is supposed to work with CommandLineTools (even without Xcode itself installed), but that's what's broken right now. 😅

It was actually two problems: The logic for finding `lldb-dap` within the toolchain was looking in the wrong directory. The second problem was that our fallback to using `xcrun` wasn't being triggered because the extension was looking for `Xcode*.app` in the toolchain path.

I've got a PR up to fix both of these issues: #1936

**Comment by joergbattermann** [comment]
Yeah I would have been surprised otherwise but just wanted to make sure I'm not missing something / "doing it wrong" (tm) 😅 

Anyway, I'll keep an eye on the PR and thanks again @matthewbastien !!

**Comment by plemarquand** [comment]
Verified with 3bfae1a244797b05c03b7d69c8213a6035f0e1af

**Comment by adam-fowler** [comment]
I am getting a similar error with latest extension when using the Xcode toolchain.
```
Failed to find lldb-dap within Swift toolchain '/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr'
```
VSCode version: 1.106.3, swift extension version: 2.14.2, Xcode 26.1.1

When I run `xcrun --find lldb-dap` it returns `/Applications/Xcode.app/Contents/Developer/usr/bin/lldb-dap` so the extension is looking in the wrong place for lldb-dap.

**Comment by matthewbastien** [comment]
@adam-fowler Are you setting `swift.path` by any chance? I think the logic that checks for an `xcrun` shim doesn't handle the case where `swift.path` points directly at the swift binary in an Xcode toolchain.

Can you upload a minimal diagnostics bundle for me to look at?

**Comment by adam-fowler** [comment]
> [@adam-fowler](https://github.com/adam-fowler) Are you setting `swift.path` by any chance? I think the logic that checks for an `xcrun` shim doesn't handle the case where `swift.path` points directly at the swift binary in an Xcode toolchain.
> 
> Can you upload a minimal diagnostics bundle for me to look at?

Choosing the Xcode toolchain sets the `swift.path`.

**Comment by matthewbastien** [comment]
For verification: the latest issue was that setting `swift.path` to an Xcode/CommandLineTools toolchain and trying to start a debug session would result in an error dialog saying that `lldb-dap` could not be found. Will need to test debugging both with and without `swift.path` being set.

**Comment by plemarquand** [comment]
Verified with 75d15112408f00bb045c956ba98cb0c8af8cf352
